//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
            this.ProjectActivities = new HashSet<ProjectActivity>();
            this.ProjectSubActivities = new HashSet<ProjectSubActivity>();
            this.ProjectExpens = new HashSet<ProjectExpens>();
            this.ProjectActivities1 = new HashSet<ProjectActivity>();
        }
    
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public string Coin { get; set; }
        public string AccountNatural { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ProjectProfile ProjectProfile { get; set; }
        public virtual ICollection<ProjectActivity> ProjectActivities { get; set; }
        public virtual ICollection<ProjectSubActivity> ProjectSubActivities { get; set; }
        public virtual ICollection<ProjectExpens> ProjectExpens { get; set; }
        public virtual ICollection<ProjectActivity> ProjectActivities1 { get; set; }
    }
}
