//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public string Coin { get; set; }
        public string AccountNatural { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ProjectActivity ProjectActivity { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ProjectProfile ProjectProfile { get; set; }
    }
}
