//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbContainer : DbContext
    {
        public dbContainer()
            : base("name=dbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserGroup> UserGroups { get; set; }
        public DbSet<UserSystem> UserSystems { get; set; }
        public DbSet<SystemPermession> SystemPermessions { get; set; }
        public DbSet<GroupPermession> GroupPermessions { get; set; }
        public DbSet<Attachment> Attachments { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<ProjectActivity> ProjectActivities { get; set; }
        public DbSet<ProjectExpens> ProjectExpenses { get; set; }
        public DbSet<ProjectOrder> ProjectOrders { get; set; }
        public DbSet<ProjectProfile> ProjectProfiles { get; set; }
        public DbSet<ProjectSubActivity> ProjectSubActivities { get; set; }
        public DbSet<Thefinancier> Thefinanciers { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<DailyMovemnt> DailyMovemnts { get; set; }
    }
}
