//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProfile
    {
        public ProjectProfile()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Contracts = new HashSet<Contract>();
            this.ProjectActivities = new HashSet<ProjectActivity>();
            this.Thefinanciers = new HashSet<Thefinancier>();
            this.Accounts = new HashSet<Account>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public int progress { get; set; }
        public double TotalCost { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<ProjectActivity> ProjectActivities { get; set; }
        public virtual ICollection<Thefinancier> Thefinanciers { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
