//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPermession
    {
        public SystemPermession()
        {
            this.GroupPermessions = new HashSet<GroupPermession>();
        }
    
        public int Id { get; set; }
        public string PermessionName { get; set; }
        public string PropertyName { get; set; }
    
        public virtual ICollection<GroupPermession> GroupPermessions { get; set; }
    }
}
