//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public System.DateTime DateOfTransaction { get; set; }
        public double TotalIn { get; set; }
        public double TotalOut { get; set; }
        public string Description { get; set; }
        public string CommandNames { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
